import type { RuleListItem } from './types';
import type { CategoryOption } from '@/components/features/transactions/types';

export interface AccountingCategoryCatalogItem {
  ledger_account: string;
  category_code: string;
  category_name: string;
  business_group: string;
  account_type: string;
  is_revenue: boolean;
  is_active: boolean;
  priority: number;
  description: string;
}

// ── Group constants ──
export const CATEGORY_GROUPS = {
  DOANH_THU_DAO_TAO: 'Doanh thu Đào tạo và Dịch vụ (TK 531, 511)',
  THU_NHAP_TAI_CHINH: 'Thu nhập Tài chính và Thu nhập khác (TK 515, 711)',
  THU_HO_CHI_HO: 'Thu hộ – Chi hộ và Phải trả khác (TK 338, 348)',
  CHI_PHI_NOI_BO: 'Chi phí & Giao dịch nội bộ',
} as const;

export const ACCOUNTING_CATEGORY_CATALOG: AccountingCategoryCatalogItem[] = [
  // ═══ Nhóm 1: Doanh thu Đào tạo và Dịch vụ (TK 531, 511) ═══
  {
    ledger_account: '5311.01',
    category_code: 'HOC_PHI',
    category_name: 'Học phí',
    business_group: CATEGORY_GROUPS.DOANH_THU_DAO_TAO,
    account_type: 'revenue',
    is_revenue: true,
    is_active: true,
    priority: 100,
    description: 'Thu học phí / Thu tiền học phí',
  },
  {
    ledger_account: '5311.02',
    category_code: 'LE_PHI_TUYEN_SINH',
    category_name: 'Lệ phí tuyển sinh',
    business_group: CATEGORY_GROUPS.DOANH_THU_DAO_TAO,
    account_type: 'revenue',
    is_revenue: true,
    is_active: true,
    priority: 100,
    description: 'Thu lệ phí xét tuyển',
  },
  {
    ledger_account: '5311.03',
    category_code: 'TIEN_HOC_LAI_THI_LAI',
    category_name: 'Tiền học lại, thi lại',
    business_group: CATEGORY_GROUPS.DOANH_THU_DAO_TAO,
    account_type: 'revenue',
    is_revenue: true,
    is_active: true,
    priority: 95,
    description: 'Thu tiền học lại thi lại',
  },
  {
    ledger_account: '5311.05',
    category_code: 'THU_NGAN_HAN',
    category_name: 'Thu ngắn hạn',
    business_group: CATEGORY_GROUPS.DOANH_THU_DAO_TAO,
    account_type: 'revenue',
    is_revenue: true,
    is_active: true,
    priority: 90,
    description: 'Thu ngắn hạn / Thu đào tạo bồi dưỡng ngắn hạn',
  },
  {
    ledger_account: '5311.07',
    category_code: 'PHI_QUAN_LY_SV_THUC_TAP',
    category_name: 'Phí quản lý HSSV thực tập',
    business_group: CATEGORY_GROUPS.DOANH_THU_DAO_TAO,
    account_type: 'revenue',
    is_revenue: true,
    is_active: true,
    priority: 90,
    description: 'Thu tiền HSSV thực tập',
  },
  {
    ledger_account: '5311.09',
    category_code: 'TUYEN_SINH_LIEN_KET',
    category_name: 'Tuyển sinh liên kết đại học',
    business_group: CATEGORY_GROUPS.DOANH_THU_DAO_TAO,
    account_type: 'revenue',
    is_revenue: true,
    is_active: true,
    priority: 85,
    description: 'Thu tiền tuyển sinh liên kết đại học',
  },
  {
    ledger_account: '5311.10',
    category_code: 'DOANH_THU_DE_AN_LIEN_DOANH',
    category_name: 'Doanh thu đề án liên doanh',
    business_group: CATEGORY_GROUPS.DOANH_THU_DAO_TAO,
    account_type: 'revenue',
    is_revenue: true,
    is_active: true,
    priority: 85,
    description: 'Thu tiền đề án liên doanh / Thu liên doanh liên kết',
  },
  {
    ledger_account: '511',
    category_code: 'DOANH_THU_NSNN',
    category_name: 'Doanh thu từ NSNN',
    business_group: CATEGORY_GROUPS.DOANH_THU_DAO_TAO,
    account_type: 'revenue',
    is_revenue: true,
    is_active: true,
    priority: 80,
    description: 'Kinh phí biên soạn giáo trình / Thu từ ngân sách nhà nước',
  },

  // ═══ Nhóm 2: Thu nhập Tài chính và Thu nhập khác (TK 515, 711) ═══
  {
    ledger_account: '515',
    category_code: 'LAI_TIEN_GUI_NGAN_HANG',
    category_name: 'Lãi tiền gửi ngân hàng',
    business_group: CATEGORY_GROUPS.THU_NHAP_TAI_CHINH,
    account_type: 'financial_income',
    is_revenue: false,
    is_active: true,
    priority: 60,
    description: 'Tiền lãi tháng / Lãi hợp đồng tiền gửi',
  },
  {
    ledger_account: '711',
    category_code: 'THU_NHAP_KHAC',
    category_name: 'Thu nhập khác',
    business_group: CATEGORY_GROUPS.THU_NHAP_TAI_CHINH,
    account_type: 'other_income',
    is_revenue: false,
    is_active: true,
    priority: 55,
    description: 'Thanh lý tài sản cố định / Thu nhập không thường xuyên khác',
  },

  // ═══ Nhóm 3: Thu hộ – Chi hộ và Phải trả khác (TK 338, 348) ═══
  {
    ledger_account: '3388.01',
    category_code: 'HOC_LIEU',
    category_name: 'Học liệu',
    business_group: CATEGORY_GROUPS.THU_HO_CHI_HO,
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 80,
    description: 'Thu học liệu online / Thu học liệu / Thu thư viện số',
  },
  {
    ledger_account: '3388.02',
    category_code: 'VAN_THE',
    category_name: 'Văn thể',
    business_group: CATEGORY_GROUPS.THU_HO_CHI_HO,
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 80,
    description: 'Thu hoạt động văn thể / Thu kinh phí Gala',
  },
  {
    ledger_account: '3388.03',
    category_code: 'TAM_THU_GIAO_TRINH',
    category_name: 'Tạm thu giáo trình',
    business_group: CATEGORY_GROUPS.THU_HO_CHI_HO,
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 80,
    description: 'Tạm thu giáo trình / Thu in ấn tài liệu',
  },
  {
    ledger_account: '3388.04',
    category_code: 'CHUYEN_NHAM_NH_TRA_VE',
    category_name: 'Chuyển nhầm, ngân hàng trả về / phải trả lại',
    business_group: CATEGORY_GROUPS.THU_HO_CHI_HO,
    account_type: 'refund_or_payable',
    is_revenue: false,
    is_active: true,
    priority: 100,
    description: 'Thu do chuyển nhầm phải trả khác / Thu tiền chuyển nhầm phải trả / Chuyển khoản trả lại tiền chuyển nhầm',
  },
  {
    ledger_account: '3388.06',
    category_code: 'BAO_HIEM_YT',
    category_name: 'Bảo hiểm y tế',
    business_group: CATEGORY_GROUPS.THU_HO_CHI_HO,
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 80,
    description: 'Thu BHYT / Thu bảo hiểm y tế HSSV',
  },
  {
    ledger_account: '3388.07',
    category_code: 'BAO_HIEM_TT',
    category_name: 'Bảo hiểm thân thể',
    business_group: CATEGORY_GROUPS.THU_HO_CHI_HO,
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 80,
    description: 'Thu BHTT',
  },
  {
    ledger_account: '3388.08',
    category_code: 'LE_PHI_KHAM_SUC_KHOE_DAU_KHOA',
    category_name: 'Lệ phí khám sức khỏe đầu khóa',
    business_group: CATEGORY_GROUPS.THU_HO_CHI_HO,
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 85,
    description: 'Thu lệ phí khám sức khỏe đầu khóa',
  },
  {
    ledger_account: '3388.09',
    category_code: 'QA_BAO_HO_LAO_DONG',
    category_name: 'Quần áo bảo hộ lao động',
    business_group: CATEGORY_GROUPS.THU_HO_CHI_HO,
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 75,
    description: 'Thu quần áo bảo hộ lao động',
  },
  {
    ledger_account: '3388.10',
    category_code: 'DONG_PHUC_TT',
    category_name: 'Đồng phục thể thao',
    business_group: CATEGORY_GROUPS.THU_HO_CHI_HO,
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 75,
    description: 'Thu đồng phục thể thao',
  },
  {
    ledger_account: '3388.11',
    category_code: 'DONG_PHUC_VAN_HOA',
    category_name: 'Đồng phục văn hóa',
    business_group: CATEGORY_GROUPS.THU_HO_CHI_HO,
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 75,
    description: 'Thu đồng phục văn hóa',
  },
  {
    ledger_account: '3388.12',
    category_code: 'AO_KHOAC',
    category_name: 'Áo khoác',
    business_group: CATEGORY_GROUPS.THU_HO_CHI_HO,
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 75,
    description: 'Thu áo khoác',
  },
  {
    ledger_account: '3388.13',
    category_code: 'THE_SINH_VIEN',
    category_name: 'Thẻ sinh viên',
    business_group: CATEGORY_GROUPS.THU_HO_CHI_HO,
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 75,
    description: 'Thu tiền thẻ sinh viên / Thu thẻ sinh viên / Thu dây đeo thẻ',
  },
  {
    ledger_account: '3388.15',
    category_code: 'CHAM_SOC_SUC_KHOE_BAN_DAU',
    category_name: 'Chăm sóc sức khỏe ban đầu',
    business_group: CATEGORY_GROUPS.THU_HO_CHI_HO,
    account_type: 'fund_or_pass_through',
    is_revenue: false,
    is_active: true,
    priority: 70,
    description: 'Thu chăm sóc sức khỏe ban đầu / Thu tiền BHXH trích CSSK ban đầu',
  },
  {
    ledger_account: '3388.17',
    category_code: 'KHUYEN_HOC_KHUYEN_TAI',
    category_name: 'Quỹ khuyến học, khuyến tài / KHKT',
    business_group: CATEGORY_GROUPS.THU_HO_CHI_HO,
    account_type: 'fund_or_pass_through',
    is_revenue: false,
    is_active: true,
    priority: 70,
    description: 'Thu quỹ khuyến học khuyến tài / Các khoản chi từ quỹ KHKT',
  },
  {
    ledger_account: '3388.19',
    category_code: 'KP_CLC',
    category_name: 'Kinh phí CLC',
    business_group: CATEGORY_GROUPS.THU_HO_CHI_HO,
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 75,
    description: 'Thu kinh phí CLC / Thu kinh phí đào tạo chất lượng cao',
  },
  {
    ledger_account: '3388.22',
    category_code: 'TIEN_DIEN',
    category_name: 'Tiền điện',
    business_group: CATEGORY_GROUPS.THU_HO_CHI_HO,
    account_type: 'pass_through_expense',
    is_revenue: false,
    is_active: true,
    priority: 65,
    description: 'Thanh toán tiền điện',
  },
  {
    ledger_account: '3388.23',
    category_code: 'TIEN_NUOC',
    category_name: 'Tiền nước',
    business_group: CATEGORY_GROUPS.THU_HO_CHI_HO,
    account_type: 'pass_through_expense',
    is_revenue: false,
    is_active: true,
    priority: 65,
    description: 'Thanh toán tiền nước sạch',
  },
  {
    ledger_account: '3388.26',
    category_code: 'THU_LAO_BHYT',
    category_name: 'Trích thù lao BHYT',
    business_group: CATEGORY_GROUPS.THU_HO_CHI_HO,
    account_type: 'fund_or_payable',
    is_revenue: false,
    is_active: true,
    priority: 65,
    description: 'Thu trích thù lao BHYT / Thanh toán tiền trích BHYT',
  },
  {
    ledger_account: '3388.34',
    category_code: 'THU_HO_DAI_HOC_BACH_KHOA',
    category_name: 'Thu hộ Đại học Bách Khoa',
    business_group: CATEGORY_GROUPS.THU_HO_CHI_HO,
    account_type: 'pass_through_receipt',
    is_revenue: false,
    is_active: true,
    priority: 90,
    description: 'Thu tiền học phí thu hộ / phải trả Đại học Bách Khoa',
  },
  {
    ledger_account: '348',
    category_code: 'DAT_COC',
    category_name: 'Đặt cọc',
    business_group: CATEGORY_GROUPS.THU_HO_CHI_HO,
    account_type: 'deposit',
    is_revenue: false,
    is_active: true,
    priority: 85,
    description: 'Thu đặt cọc học nghề / Thu đặt cọc đề án liên kết',
  },

  // ═══ Nhóm 4: Chi phí & Giao dịch nội bộ ═══
  {
    ledger_account: '615',
    category_code: 'PHI_DICH_VU_NGAN_HANG',
    category_name: 'Phí dịch vụ ngân hàng',
    business_group: CATEGORY_GROUPS.CHI_PHI_NOI_BO,
    account_type: 'bank_expense',
    is_revenue: false,
    is_active: true,
    priority: 60,
    description: 'Phí duy trì SMS Banking / Phí dịch vụ Agribank Plus / Phí quản lý tài khoản',
  },
  {
    ledger_account: '6428',
    category_code: 'PHI_CHUYEN_KHOAN',
    category_name: 'Phí chuyển khoản',
    business_group: CATEGORY_GROUPS.CHI_PHI_NOI_BO,
    account_type: 'bank_expense',
    is_revenue: false,
    is_active: true,
    priority: 60,
    description: 'Phí chuyển khoản',
  },
  {
    ledger_account: '632.01',
    category_code: 'CHI_PHI_DAO_TAO_NVSP',
    category_name: 'Chi phí đào tạo / tuyển sinh NVSP',
    business_group: CATEGORY_GROUPS.CHI_PHI_NOI_BO,
    account_type: 'program_expense',
    is_revenue: false,
    is_active: true,
    priority: 50,
    description: 'Thanh toán tiền giảng dạy / tuyển sinh / nộp thuế TNCN lớp NVSP',
  },
  {
    ledger_account: '632.09',
    category_code: 'CHI_PHI_LIEN_KET_DHSP_HY',
    category_name: 'Chi phí tuyển sinh, QLĐT liên kết ĐHSP KT Hưng Yên',
    business_group: CATEGORY_GROUPS.CHI_PHI_NOI_BO,
    account_type: 'program_expense',
    is_revenue: false,
    is_active: true,
    priority: 50,
    description: 'Thanh toán tiền tuyển sinh và QLĐT lớp liên kết ĐHSP KT Hưng Yên',
  },
  {
    ledger_account: '1211',
    category_code: 'HOP_DONG_TIEN_GUI',
    category_name: 'Hợp đồng tiền gửi',
    business_group: CATEGORY_GROUPS.CHI_PHI_NOI_BO,
    account_type: 'internal_financial_transfer',
    is_revenue: false,
    is_active: true,
    priority: 40,
    description: 'Mở HĐTG / Tất toán hợp đồng tiền gửi',
  },
  {
    ledger_account: '1111',
    category_code: 'NOP_TIEN_MAT_VAO_NGAN_HANG',
    category_name: 'Nộp tiền mặt vào ngân hàng',
    business_group: CATEGORY_GROUPS.CHI_PHI_NOI_BO,
    account_type: 'internal_transfer',
    is_revenue: false,
    is_active: true,
    priority: 40,
    description: 'Chi nộp tiền vào tài khoản ngân hàng',
  },
  {
    ledger_account: '1121.05',
    category_code: 'CHUYEN_KHOAN_NOI_BO',
    category_name: 'Chuyển khoản nội bộ',
    business_group: CATEGORY_GROUPS.CHI_PHI_NOI_BO,
    account_type: 'internal_transfer',
    is_revenue: false,
    is_active: true,
    priority: 40,
    description: 'Chuyển tiền nội bộ giữa các tài khoản ngân hàng',
  },
];

const toNoAccentLower = (value: string): string =>
  value
    .normalize('NFD')
    .replace(/\p{M}+/gu, '')
    .replace(/đ/g, 'd')
    .replace(/Đ/g, 'D')
    .toLowerCase();

const toKeyword = (description: string): string =>
  toNoAccentLower(description)
    .replace(/\s*\/\s*/g, '|')
    .replace(/\s+/g, ' ')
    .trim();

export const MOCK_CATEGORIES: CategoryOption[] = [
  ...ACCOUNTING_CATEGORY_CATALOG.map((item, idx) => ({
    id: `cat-${String(idx + 1).padStart(3, '0')}`,
    code: item.category_code,
    name: item.category_name,
    group: item.business_group,
    ledger_account: item.ledger_account,
  })),
  {
    id: `cat-${String(ACCOUNTING_CATEGORY_CATALOG.length + 1).padStart(3, '0')}`,
    code: 'OTHER',
    name: 'Khác / Chưa xác định',
    group: 'Khác',
  },
];

// Helper to resolve category_id and category_name from code
function resolveCat(code: string) {
  const idx = ACCOUNTING_CATEGORY_CATALOG.findIndex((c) => c.category_code === code);
  if (idx >= 0) {
    return {
      category_id: `cat-${String(idx + 1).padStart(3, '0')}`,
      category_name: ACCOUNTING_CATEGORY_CATALOG[idx].category_name,
    };
  }
  // Fallback to OTHER
  return {
    category_id: `cat-${String(ACCOUNTING_CATEGORY_CATALOG.length + 1).padStart(3, '0')}`,
    category_name: 'Khác / Chưa xác định',
  };
}

export const MOCK_RULES: RuleListItem[] = [
  {
    id: 'rule-001',
    ...resolveCat('TIEN_HOC_LAI_THI_LAI'),
    category_code: 'TIEN_HOC_LAI_THI_LAI',
    keyword: 'hoc lai|tien hoc lai|dong tien hoc lai|chuyen tien hoc lai|thi lai',
    type: 'keyword',
    priority: 1,
    amount_min: null,
    amount_max: null,
    conditions: null,
    stop_on_match: true,
    is_active: true,
    match_count: 0,
    created_at: '2026-03-13T00:00:00Z',
    updated_at: '2026-03-13T00:00:00Z',
  },
  {
    id: 'rule-002',
    ...resolveCat('TIEN_HOC_LAI_THI_LAI'),
    category_code: 'TIEN_HOC_LAI_THI_LAI',
    keyword: '(hoc\\s+lai|thi\\s+lai).*(mon|tieng anh|giao duc chinh tri|nguoi co ban|ve ky thuat|vi dieu khien|trang diem tham my|to chuc va quan tri san xuat kinh doanh|truyen dong dien|tieng anh chuyen nganh)',
    type: 'regex',
    priority: 2,
    amount_min: null,
    amount_max: null,
    conditions: null,
    stop_on_match: true,
    is_active: true,
    match_count: 0,
    created_at: '2026-03-13T00:00:00Z',
    updated_at: '2026-03-13T00:00:00Z',
  },
  {
    id: 'rule-003',
    ...resolveCat('BAO_HIEM_YT'),
    category_code: 'BAO_HIEM_YT',
    keyword: 'bhyt|bao hiem y te|tien bhyt|dong tien bao hiem y te|ck tien bhyt',
    type: 'keyword',
    priority: 3,
    amount_min: null,
    amount_max: null,
    conditions: null,
    stop_on_match: true,
    is_active: true,
    match_count: 0,
    created_at: '2026-03-13T00:00:00Z',
    updated_at: '2026-03-13T00:00:00Z',
  },
  {
    id: 'rule-004',
    ...resolveCat('BAO_HIEM_YT'),
    category_code: 'BAO_HIEM_YT',
    keyword: '(bhyt|bao\\s*hiem\\s*y\\s*te)',
    type: 'regex',
    priority: 4,
    amount_min: 100000,
    amount_max: 2000000,
    conditions: null,
    stop_on_match: true,
    is_active: true,
    match_count: 0,
    created_at: '2026-03-13T00:00:00Z',
    updated_at: '2026-03-13T00:00:00Z',
  },
  {
    id: 'rule-005',
    ...resolveCat('HOC_PHI'),
    category_code: 'HOC_PHI',
    keyword: '@va_.*hd(2775000|3024000|4536000|7200000|8800000|9080000|9250000|9280000)vnd',
    type: 'regex',
    priority: 5,
    amount_min: null,
    amount_max: null,
    conditions: null,
    stop_on_match: true,
    is_active: true,
    match_count: 0,
    created_at: '2026-03-13T00:00:00Z',
    updated_at: '2026-03-13T00:00:00Z',
  },
  {
    id: 'rule-006',
    ...resolveCat('HOC_PHI'),
    category_code: 'HOC_PHI',
    keyword: '(hp\\s*ky|hoc\\s*phi|nop\\s*hp).*(k49|cd47|cd48|cd49)',
    type: 'regex',
    priority: 6,
    amount_min: null,
    amount_max: null,
    conditions: null,
    stop_on_match: true,
    is_active: true,
    match_count: 0,
    created_at: '2026-03-13T00:00:00Z',
    updated_at: '2026-03-13T00:00:00Z',
  },
  {
    id: 'rule-007',
    ...resolveCat('HOC_PHI'),
    category_code: 'HOC_PHI',
    keyword: 'k49|hp ky|nop hp|hoc phi|ltdh k49',
    type: 'composite',
    priority: 7,
    amount_min: 2500000,
    amount_max: 9500000,
    conditions: null,
    stop_on_match: true,
    is_active: true,
    match_count: 0,
    created_at: '2026-03-13T00:00:00Z',
    updated_at: '2026-03-13T00:00:00Z',
  },
  {
    id: 'rule-008',
    ...resolveCat('DOANH_THU_DE_AN_LIEN_DOANH'),
    category_code: 'DOANH_THU_DE_AN_LIEN_DOANH',
    keyword: 'hd so|hop dong so|hd-cdncn|cdncn|nop hd|thanh toan hd|thanh toan tien thue csvc|nop tien thue dat|quy 1 nam 2026|tu thang 01 den thang 03 2026',
    type: 'keyword',
    priority: 10,
    amount_min: 4000000,
    amount_max: null,
    conditions: null,
    stop_on_match: true,
    is_active: true,
    match_count: 0,
    created_at: '2026-03-13T00:00:00Z',
    updated_at: '2026-03-13T00:00:00Z',
  },
  {
    id: 'rule-009',
    ...resolveCat('DOANH_THU_DE_AN_LIEN_DOANH'),
    category_code: 'DOANH_THU_DE_AN_LIEN_DOANH',
    keyword: '(cong ty|ctcp|cty tnhh|beauty|ascs|mai anh|khoa bang).*(hd\\s*so|hop dong|cdncn|thanh toan)',
    type: 'regex',
    priority: 11,
    amount_min: null,
    amount_max: null,
    conditions: null,
    stop_on_match: true,
    is_active: true,
    match_count: 0,
    created_at: '2026-03-13T00:00:00Z',
    updated_at: '2026-03-13T00:00:00Z',
  },
  {
    id: 'rule-010',
    ...resolveCat('CHI_PHI_DAO_TAO_NVSP'),
    category_code: 'CHI_PHI_DAO_TAO_NVSP',
    keyword: 'nvsp|hoc phi lop nvsp|nop hoc phi lop nvsp|so cap',
    type: 'keyword',
    priority: 15,
    amount_min: null,
    amount_max: null,
    conditions: null,
    stop_on_match: true,
    is_active: true,
    match_count: 0,
    created_at: '2026-03-13T00:00:00Z',
    updated_at: '2026-03-13T00:00:00Z',
  },
  {
    id: 'rule-011',
    ...resolveCat('THU_NGAN_HAN'),
    category_code: 'THU_NGAN_HAN',
    keyword: 'hoc phi ngan han|ngan han|lop ngan han',
    type: 'keyword',
    priority: 16,
    amount_min: null,
    amount_max: null,
    conditions: null,
    stop_on_match: true,
    is_active: true,
    match_count: 0,
    created_at: '2026-03-13T00:00:00Z',
    updated_at: '2026-03-13T00:00:00Z',
  },
  {
    id: 'rule-012',
    ...resolveCat('TAM_THU_GIAO_TRINH'),
    category_code: 'TAM_THU_GIAO_TRINH',
    keyword: 'tien gt|giao trinh|tien giao trinh|giao trinh bo sung',
    type: 'keyword',
    priority: 17,
    amount_min: null,
    amount_max: null,
    conditions: null,
    stop_on_match: true,
    is_active: true,
    match_count: 0,
    created_at: '2026-03-13T00:00:00Z',
    updated_at: '2026-03-13T00:00:00Z',
  },
  {
    id: 'rule-013',
    ...resolveCat('PHI_DICH_VU_NGAN_HANG'),
    category_code: 'PHI_DICH_VU_NGAN_HANG',
    keyword: 'phi quan ly tai khoan|phi bsms|thu phi duy tri dich vu|phi dich vu',
    type: 'keyword',
    priority: 50,
    amount_min: null,
    amount_max: null,
    conditions: null,
    stop_on_match: true,
    is_active: true,
    match_count: 0,
    created_at: '2026-03-13T00:00:00Z',
    updated_at: '2026-03-13T00:00:00Z',
  },
  {
    id: 'rule-014',
    ...resolveCat('CHUYEN_KHOAN_NOI_BO'),
    category_code: 'CHUYEN_KHOAN_NOI_BO',
    keyword: '@@.*@@_thuho_',
    type: 'regex',
    priority: 60,
    amount_min: null,
    amount_max: null,
    conditions: null,
    stop_on_match: true,
    is_active: true,
    match_count: 0,
    created_at: '2026-03-13T00:00:00Z',
    updated_at: '2026-03-13T00:00:00Z',
  },
  {
    id: 'rule-015',
    ...resolveCat('CHUYEN_KHOAN_NOI_BO'),
    category_code: 'CHUYEN_KHOAN_NOI_BO',
    keyword: '@@.*@@_chiho_',
    type: 'regex',
    priority: 61,
    amount_min: null,
    amount_max: null,
    conditions: null,
    stop_on_match: true,
    is_active: true,
    match_count: 0,
    created_at: '2026-03-13T00:00:00Z',
    updated_at: '2026-03-13T00:00:00Z',
  },
  {
    id: 'rule-016',
    ...resolveCat('OTHER'),
    category_code: 'OTHER',
    keyword: '',
    type: 'fallback',
    priority: 999,
    amount_min: null,
    amount_max: null,
    conditions: null,
    stop_on_match: true,
    is_active: true,
    match_count: 0,
    created_at: '2026-03-13T00:00:00Z',
    updated_at: '2026-03-13T00:00:00Z',
  },
];
