import type { RuleListItem, CategoryOption } from './types';

export interface AccountingCategoryCatalogItem {
  ledger_account: string;
  category_code: string;
  category_name: string;
  business_group: string;
  account_type: string;
  is_revenue: boolean;
  is_active: boolean;
  priority: number;
  description: string;
}

export const ACCOUNTING_CATEGORY_CATALOG: AccountingCategoryCatalogItem[] = [
  {
    ledger_account: '5311.01',
    category_code: 'HOC_PHI',
    category_name: 'Học phí',
    business_group: 'Doanh thu trực tiếp',
    account_type: 'revenue',
    is_revenue: true,
    is_active: true,
    priority: 100,
    description: 'Thu học phí / Thu tiền học phí',
  },
  {
    ledger_account: '5311.02',
    category_code: 'LE_PHI_TUYEN_SINH',
    category_name: 'Lệ phí tuyển sinh',
    business_group: 'Doanh thu trực tiếp',
    account_type: 'revenue',
    is_revenue: true,
    is_active: true,
    priority: 100,
    description: 'Thu lệ phí xét tuyển',
  },
  {
    ledger_account: '5311.03',
    category_code: 'TIEN_HOC_LAI_THI_LAI',
    category_name: 'Tiền học lại, thi lại',
    business_group: 'Doanh thu trực tiếp',
    account_type: 'revenue',
    is_revenue: true,
    is_active: true,
    priority: 95,
    description: 'Thu tiền học lại thi lại',
  },
  {
    ledger_account: '5311.05',
    category_code: 'THU_NGAN_HAN',
    category_name: 'Thu ngắn hạn',
    business_group: 'Doanh thu trực tiếp',
    account_type: 'revenue',
    is_revenue: true,
    is_active: true,
    priority: 90,
    description: 'Thu ngắn hạn',
  },
  {
    ledger_account: '5311.07',
    category_code: 'PHI_QUAN_LY_SV_THUC_TAP',
    category_name: 'Phí quản lý HSSV thực tập',
    business_group: 'Doanh thu trực tiếp',
    account_type: 'revenue',
    is_revenue: true,
    is_active: true,
    priority: 90,
    description: 'Thu tiền HSSV thực tập',
  },
  {
    ledger_account: '5311.09',
    category_code: 'TUYEN_SINH_LIEN_KET',
    category_name: 'Tuyển sinh liên kết đại học',
    business_group: 'Doanh thu trực tiếp',
    account_type: 'revenue',
    is_revenue: true,
    is_active: true,
    priority: 85,
    description: 'Thu tiền tuyển sinh liên kết đại học',
  },
  {
    ledger_account: '3388.01',
    category_code: 'HOC_LIEU',
    category_name: 'Học liệu',
    business_group: 'Tạm thu / thu kèm nhập học',
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 80,
    description: 'Thu học liệu online / Thu học liệu',
  },
  {
    ledger_account: '3388.02',
    category_code: 'VAN_THE',
    category_name: 'Văn thể',
    business_group: 'Tạm thu / thu kèm nhập học',
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 80,
    description: 'Thu hoạt động văn thể',
  },
  {
    ledger_account: '3388.03',
    category_code: 'TAM_THU_GIAO_TRINH',
    category_name: 'Tạm thu giáo trình',
    business_group: 'Tạm thu / thu kèm nhập học',
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 80,
    description: 'Tạm thu giáo trình',
  },
  {
    ledger_account: '3388.04',
    category_code: 'CHUYEN_NHAM_NH_TRA_VE',
    category_name: 'Chuyển nhầm, ngân hàng trả về / phải trả lại',
    business_group: 'Thu hộ / phải trả',
    account_type: 'refund_or_payable',
    is_revenue: false,
    is_active: true,
    priority: 100,
    description: 'Thu do chuyển nhầm phải trả khác / Thu tiền chuyển nhầm phải trả / Chuyển khoản trả lại tiền chuyển nhầm',
  },
  {
    ledger_account: '3388.06',
    category_code: 'BAO_HIEM_YT',
    category_name: 'Bảo hiểm y tế',
    business_group: 'Tạm thu / thu kèm nhập học',
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 80,
    description: 'Thu BHYT',
  },
  {
    ledger_account: '3388.07',
    category_code: 'BAO_HIEM_TT',
    category_name: 'Bảo hiểm thân thể',
    business_group: 'Tạm thu / thu kèm nhập học',
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 80,
    description: 'Thu BHTT',
  },
  {
    ledger_account: '3388.08',
    category_code: 'LE_PHI_KHAM_SUC_KHOE_DAU_KHOA',
    category_name: 'Lệ phí khám sức khỏe đầu khóa',
    business_group: 'Tạm thu / thu kèm nhập học',
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 85,
    description: 'Thu lệ phí khám sức khỏe đầu khóa',
  },
  {
    ledger_account: '3388.09',
    category_code: 'QA_BAO_HO_LAO_DONG',
    category_name: 'Quần áo bảo hộ lao động',
    business_group: 'Tạm thu / thu kèm nhập học',
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 75,
    description: 'Thu quần áo bảo hộ lao động',
  },
  {
    ledger_account: '3388.10',
    category_code: 'DONG_PHUC_TT',
    category_name: 'Đồng phục thể thao',
    business_group: 'Tạm thu / thu kèm nhập học',
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 75,
    description: 'Thu đồng phục thể thao',
  },
  {
    ledger_account: '3388.11',
    category_code: 'DONG_PHUC_VAN_HOA',
    category_name: 'Đồng phục văn hóa',
    business_group: 'Tạm thu / thu kèm nhập học',
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 75,
    description: 'Thu đồng phục văn hóa',
  },
  {
    ledger_account: '3388.12',
    category_code: 'AO_KHOAC',
    category_name: 'Áo khoác',
    business_group: 'Tạm thu / thu kèm nhập học',
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 75,
    description: 'Thu áo khoác',
  },
  {
    ledger_account: '3388.13',
    category_code: 'THE_SINH_VIEN',
    category_name: 'Thẻ sinh viên',
    business_group: 'Tạm thu / thu kèm nhập học',
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 75,
    description: 'Thu tiền thẻ sinh viên / Thu thẻ sinh viên',
  },
  {
    ledger_account: '3388.15',
    category_code: 'CHAM_SOC_SUC_KHOE_BAN_DAU',
    category_name: 'Chăm sóc sức khỏe ban đầu',
    business_group: 'Thu hộ / quỹ sức khỏe',
    account_type: 'fund_or_pass_through',
    is_revenue: false,
    is_active: true,
    priority: 70,
    description: 'Thu chăm sóc sức khỏe ban đầu / Thu tiền BHXH trích CSSK ban đầu',
  },
  {
    ledger_account: '3388.17',
    category_code: 'KHUYEN_HOC_KHUYEN_TAI',
    category_name: 'Quỹ khuyến học, khuyến tài / KHKT',
    business_group: 'Quỹ nội bộ / thu hộ mục đích riêng',
    account_type: 'fund_or_pass_through',
    is_revenue: false,
    is_active: true,
    priority: 70,
    description: 'Thu quỹ khuyến học khuyến tài / Các khoản chi từ quỹ KHKT',
  },
  {
    ledger_account: '3388.19',
    category_code: 'KP_CLC',
    category_name: 'Kinh phí CLC',
    business_group: 'Khoản thu chuyên đề / chương trình CLC',
    account_type: 'temporary_receipt',
    is_revenue: false,
    is_active: true,
    priority: 75,
    description: 'Thu kinh phí CLC',
  },
  {
    ledger_account: '3388.22',
    category_code: 'TIEN_DIEN',
    category_name: 'Tiền điện',
    business_group: 'Thu hộ / chi hộ tiện ích',
    account_type: 'pass_through_expense',
    is_revenue: false,
    is_active: true,
    priority: 65,
    description: 'Thanh toán tiền điện',
  },
  {
    ledger_account: '3388.23',
    category_code: 'TIEN_NUOC',
    category_name: 'Tiền nước',
    business_group: 'Thu hộ / chi hộ tiện ích',
    account_type: 'pass_through_expense',
    is_revenue: false,
    is_active: true,
    priority: 65,
    description: 'Thanh toán tiền nước sạch',
  },
  {
    ledger_account: '3388.26',
    category_code: 'THU_LAO_BHYT',
    category_name: 'Trích thù lao BHYT',
    business_group: 'Khoản phải theo dõi riêng',
    account_type: 'fund_or_payable',
    is_revenue: false,
    is_active: true,
    priority: 65,
    description: 'Thu trích thù lao BHYT / Thanh toán tiền trích BHYT',
  },
  {
    ledger_account: '3388.34',
    category_code: 'THU_HO_DAI_HOC_BACH_KHOA',
    category_name: 'Thu hộ Đại học Bách Khoa',
    business_group: 'Thu hộ / phải trả',
    account_type: 'pass_through_receipt',
    is_revenue: false,
    is_active: true,
    priority: 90,
    description: 'Thu tiền học phí thu hộ / phải trả Đại học Bách Khoa',
  },
  {
    ledger_account: '348',
    category_code: 'DAT_COC',
    category_name: 'Đặt cọc',
    business_group: 'Khoản phải theo dõi riêng',
    account_type: 'deposit',
    is_revenue: false,
    is_active: true,
    priority: 85,
    description: 'Thu đặt cọc học nghề',
  },
  {
    ledger_account: '515',
    category_code: 'LAI_TIEN_GUI_NGAN_HANG',
    category_name: 'Lãi tiền gửi ngân hàng',
    business_group: 'Doanh thu tài chính',
    account_type: 'financial_income',
    is_revenue: false,
    is_active: true,
    priority: 60,
    description: 'Tiền lãi tháng / Lãi hợp đồng tiền gửi',
  },
  {
    ledger_account: '615',
    category_code: 'PHI_DICH_VU_NGAN_HANG',
    category_name: 'Phí dịch vụ ngân hàng',
    business_group: 'Chi phí ngân hàng',
    account_type: 'bank_expense',
    is_revenue: false,
    is_active: true,
    priority: 60,
    description: 'Phí duy trì SMS Banking / Phí dịch vụ Agribank Plus / Phí quản lý tài khoản',
  },
  {
    ledger_account: '6428',
    category_code: 'PHI_CHUYEN_KHOAN',
    category_name: 'Phí chuyển khoản',
    business_group: 'Chi phí ngân hàng',
    account_type: 'bank_expense',
    is_revenue: false,
    is_active: true,
    priority: 60,
    description: 'Phí chuyển khoản',
  },
  {
    ledger_account: '632.01',
    category_code: 'CHI_PHI_DAO_TAO_NVSP',
    category_name: 'Chi phí đào tạo / tuyển sinh NVSP',
    business_group: 'Chi phí chương trình đào tạo',
    account_type: 'program_expense',
    is_revenue: false,
    is_active: true,
    priority: 50,
    description: 'Thanh toán tiền giảng dạy / tuyển sinh / nộp thuế TNCN lớp NVSP',
  },
  {
    ledger_account: '632.09',
    category_code: 'CHI_PHI_LIEN_KET_DHSP_HY',
    category_name: 'Chi phí tuyển sinh, QLĐT liên kết ĐHSP KT Hưng Yên',
    business_group: 'Chi phí chương trình liên kết',
    account_type: 'program_expense',
    is_revenue: false,
    is_active: true,
    priority: 50,
    description: 'Thanh toán tiền tuyển sinh và QLĐT lớp liên kết ĐHSP KT Hưng Yên',
  },
  {
    ledger_account: '1211',
    category_code: 'HOP_DONG_TIEN_GUI',
    category_name: 'Hợp đồng tiền gửi',
    business_group: 'Giao dịch nội bộ tài chính',
    account_type: 'internal_financial_transfer',
    is_revenue: false,
    is_active: true,
    priority: 40,
    description: 'Mở HĐTG / Tất toán hợp đồng tiền gửi',
  },
  {
    ledger_account: '1111',
    category_code: 'NOP_TIEN_MAT_VAO_NGAN_HANG',
    category_name: 'Nộp tiền mặt vào ngân hàng',
    business_group: 'Giao dịch nội bộ',
    account_type: 'internal_transfer',
    is_revenue: false,
    is_active: true,
    priority: 40,
    description: 'Chi nộp tiền vào tài khoản ngân hàng',
  },
  {
    ledger_account: '1121.05',
    category_code: 'CHUYEN_KHOAN_NOI_BO',
    category_name: 'Chuyển khoản nội bộ',
    business_group: 'Giao dịch nội bộ',
    account_type: 'internal_transfer',
    is_revenue: false,
    is_active: true,
    priority: 40,
    description: 'Chuyển tiền nội bộ giữa các tài khoản ngân hàng',
  },
];

const toNoAccentLower = (value: string): string =>
  value
    .normalize('NFD')
    .replace(/\p{M}+/gu, '')
    .replace(/đ/g, 'd')
    .replace(/Đ/g, 'D')
    .toLowerCase();

const toKeyword = (description: string): string =>
  toNoAccentLower(description)
    .replace(/\s*\/\s*/g, '|')
    .replace(/\s+/g, ' ')
    .trim();

export const MOCK_CATEGORIES: CategoryOption[] = [
  ...ACCOUNTING_CATEGORY_CATALOG.map((item, idx) => ({
    id: `cat-${String(idx + 1).padStart(3, '0')}`,
    code: item.category_code,
    name: item.category_name,
  })),
  {
    id: `cat-${String(ACCOUNTING_CATEGORY_CATALOG.length + 1).padStart(3, '0')}`,
    code: 'OTHER',
    name: 'Khác / Chưa xác định',
  },
];

export const MOCK_RULES: RuleListItem[] = [
  ...ACCOUNTING_CATEGORY_CATALOG.map((item, idx) => ({
    id: `rule-${String(idx + 1).padStart(3, '0')}`,
    category_id: `cat-${String(idx + 1).padStart(3, '0')}`,
    category_code: item.category_code,
    category_name: item.category_name,
    keyword: toKeyword(item.description),
    type: 'keyword' as const,
    priority: idx + 1,
    amount_min: null,
    amount_max: null,
    conditions: {
      ledger_account: item.ledger_account,
      business_group: item.business_group,
      account_type: item.account_type,
      source_priority: item.priority,
      is_revenue: item.is_revenue,
    },
    stop_on_match: true,
    is_active: item.is_active,
    match_count: 0,
    created_at: '2025-12-01T00:00:00Z',
    updated_at: '2025-12-31T00:00:00Z',
  })),
  {
    id: `rule-${String(ACCOUNTING_CATEGORY_CATALOG.length + 1).padStart(3, '0')}`,
    category_id: `cat-${String(ACCOUNTING_CATEGORY_CATALOG.length + 1).padStart(3, '0')}`,
    category_code: 'OTHER',
    category_name: 'Khác / Chưa xác định',
    keyword: '',
    type: 'fallback',
    priority: 999,
    amount_min: null,
    amount_max: null,
    conditions: null,
    stop_on_match: false,
    is_active: true,
    match_count: 0,
    created_at: '2025-12-01T00:00:00Z',
    updated_at: '2025-12-31T00:00:00Z',
  },
];
